### ISSUE TITLE
IPv6支持

### ISSUE THREAD

**Issue by saginardo** [lbp0200/PRCDNS#4]
使用了几天，配合pdnsd在路由器上面使用效果超好，但是发现好像不能解析IPv6地址，dig了一下AAAA也没有结果，不知道是不是暂时不支持IPv6查询，后期有支持计划么？

**Comment by lbp0200** [comment]
另起了一个项目，应该支持IPV6，有问题反馈我。

https://github.com/lbp0200/prc-dns
