### ISSUE TITLE
有几个问题请教一下。

### ISSUE THREAD

**Issue by tec1987** [lbp0200/PRCDNS#5]
1、可否在本机python环境下直接运行？ Win系统 已装py3
2、对于动态出口的二级ISP（长宽等），使用一些ip查询网站返回的结果不一定相同(可能是移动、联通或者电信出口)，建议使用一些CDN友好的ip查询网站查询ip：
    http://ip.6655.com/ip.aspx
    http://myip.dnsomatic.com/
    http://www.trackip.net/ip
原则上能返回离你最近的出口IP就好

3、使用测试服务器，edns_client_subnet用的是VPS的IP？
> C:\>dig @23.106.151.177 +vc -p 3535 +noall +answer www.akamai.com
> www.akamai.com.         86      IN      CNAME   www.akamai.com.edgekey.net.
> www.akamai.com.edgekey.net. 8910 IN     CNAME   www.akamai.com.edgekey.net.globalredir.akadns.net.
> www.akamai.com.edgekey.net.globalredir.akadns.net. 3599 IN CNAME e1699.dscc.akamaiedge.net.
> e1699.dscc.akamaiedge.net. 19   IN      A       104.68.100.10

> C:\>dig @23.106.151.177 +vc -p 3535 +noall +answer www.akamai.com
> www.akamai.com.         198     IN      CNAME   www.akamai.com.edgekey.net.
> www.akamai.com.edgekey.net. 7513 IN     CNAME   www.akamai.com.edgekey.net.globalredir.akadns.net.
> www.akamai.com.edgekey.net.globalredir.akadns.net. 3598 IN CNAME e1699.dscc.akamaiedge.net.
> e1699.dscc.akamaiedge.net. 18   IN      A       23.214.28.100
> 
> C:\>dig +noall +answer www.akamai.com
> www.akamai.com.         217     IN      CNAME   www.akamai.com.edgekey.net.
> www.akamai.com.edgekey.net. 17176 IN    CNAME   www.akamai.com.edgekey.net.globalredir.akadns.net.
> www.akamai.com.edgekey.net.globalredir.akadns.net. 769 IN CNAME e1699.dscca.s.tl88.net.
> e1699.dscca.s.tl88.net. 60      IN      A       219.154.72.76

另外，如果本机直连dns.google.com，不用加edns_client_subnet，google会自动判断来源IP，可以比较方便的在本地做防污染DNS

**Comment by lbp0200** [comment]
@tec1987 
1、可以的，不过我没有在Windows上试过，应该配合UNbound使用
2、多接口多IP对比，判断最近的IP难度太大，我不确定能搞定，而且意义不大，只要不出PRC局域网，速度都差不多。
3、不写`-r`参数，就是本机直连dns.google.com，问题是：连不上。

**Comment by lbp0200** [comment]
@tec1987 
2、我可以尝试换成ip138

**Comment by lbp0200** [comment]
@tec1987 
已更新，换用淘宝接口获取IP，但是只有在本机或局域网内有效。

**Comment by tec1987** [comment]
@lbp0200 
感谢解答，我抽时间在Win平台测试一下。
现在使用的是Unbound将被污染域名转发到OpenDNS，以前用DNSCrypt，可惜不支持CDN
目前长宽的网络，OpenDNS丢包严重，不知道还能使用多久。。。

其实我的想法是：用curl，或者写hosts，直连GGC即可
curl -sm2 --resolve dns.google.com:443:122.202.129.185 https://dns.google.com/resolve?name=g.cn

**Comment by lbp0200** [comment]
@tec1987 还能这么玩？我研究下

**Comment by lbp0200** [comment]
@tec1987 绑定hosts之后，直接运行`PRCDNS`即可。
