### ISSUE TITLE
觉得还是不太靠谱

### ISSUE THREAD

**Issue by JayceCao** [lbp0200/PRCDNS#6]
刚刚用`pdnsd + PRCDNS`搭建完成试了一下，我是帝都电信，结果某度的cdn被解析到江苏节点去了。。。pdnsd的备用服务器是114，主上游服务器是PRCDNS，vps在国外。

**Comment by lbp0200** [comment]
@JayceCao 刚刚更新了获取公网IP的接口，我不确定你现在是否使用了最新版，使用了哪个接口。
可以都试试，http://ipinfo.io/json和http://ip.taobao.com/service/getIpInfo.php?ip=myip，看下自己的公网IP，在Google的接口里查一下，https://dns.google.com/resolve?name=域名&edns_client_subnet=你的IP/24

**Comment by JayceCao** [comment]
@lbp0200 简单看了一下源码，用获取公网IP的接口获取到的IP似乎是PRCDNS所在的服务器的IP地址？

**Comment by lbp0200** [comment]
@JayceCao PRCDNS放到了国外？那就是本机访问vps，vps看到的ip。

**Comment by JayceCao** [comment]
我是这样配置的：pdnsd做前端，其主上游服务器是通过本地访问PRCDNS，对外是没有开放PRCDNS的端口的。所以外部直接访问的是pdsnd。然后PRCDNS是最新版本。pdnsd和PRCDNS是在同一台国外VPS。我把服务器的ip发到你的email了，你可以试一下。pdnsd的配置文件是按照你的博客上的配置写的。

**Comment by maojy** [comment]
@JayceCao 你pdnsd跟PRCDNS都在远程服务器上，并且客户端是先访问pdnsd 然后 pdnsd去向PRCDNS查询，这样设置的结果应该是PRCDNS认为是服务器本身去请求dns.google.com的，所以带过去的edns客户端IP会是你VPS的，而不是你请求pdnsd的IP

**Comment by lbp0200** [comment]
@JayceCao pdnsd应该放在帝都——你的局域网里面，这样才能起作用。
