### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by jyuny1** [lbp0200/PRCDNS#7]
使用 -r 到自己的 proxy server 后发现问题
![screen shot 2017-03-18 at 1 01 04 am](https://cloud.githubusercontent.com/assets/94984/24054203/61b634f8-0b76-11e7-8943-9fb18139f292.png)

**Comment by lbp0200** [comment]
@jyuny1 是不是用的GoAgent？

**Comment by tec1987** [comment]
@jyuny1 
aiohttp证书链的处理似乎有问题，我这面使用代理或者GGC的IP时也会出现此问题：
https://stackoverflow.com/questions/29827642/asynchronous-aiohttp-requests-fails-but-synchronous-requests-succeed

修改proxy_client.py，禁用SSL验证：

21行：
`async with aiohttp.ClientSession(connector=aiohttp.TCPConnector(verify_ssl=False)) as session:`

26行：
`async with aiohttp.ClientSession(loop=loop, connector=aiohttp.TCPConnector(verify_ssl=False)) as session:
`
